In [50]:
import numpy as np
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
from PIL import Image

TensorFlow version: 2.9.1


In [31]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [32]:
x_train.shape, x_test.shape

((60000, 28, 28), (10000, 28, 28))

In [33]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [34]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.36607268, -0.43736827,  0.14182636,  0.2937255 ,  0.03912888,
        -0.02705115,  0.5174899 , -0.52218664,  0.2760753 ,  0.6373771 ]],
      dtype=float32)

In [35]:
tf.nn.softmax(predictions).numpy()

array([[0.06122288, 0.05700992, 0.10173995, 0.11842965, 0.09181012,
        0.08593082, 0.14812902, 0.05237383, 0.11635769, 0.16699615]],
      dtype=float32)

In [36]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.4542127

In [37]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [38]:
model.fit(x_train, y_train, epochs=8)

Epoch 1/8


2022-08-20 02:53:10.784805: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 [==============================] - 4s 2ms/step - loss: 0.2961 - accuracy: 0.9139
Epoch 2/8
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1417 - accuracy: 0.9573
Epoch 3/8
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1061 - accuracy: 0.9672
Epoch 4/8
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0866 - accuracy: 0.9736
Epoch 5/8
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0757 - accuracy: 0.9763
Epoch 6/8
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0661 - accuracy: 0.9790
Epoch 7/8
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0593 - accuracy: 0.9810
Epoch 8/8
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0526 - accuracy: 0.9832


In [39]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0680 - accuracy: 0.9796 - 601ms/epoch - 2ms/step


[0.06800022721290588, 0.9796000123023987]

In [40]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [73]:
probability_model(x_test[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[2.5670678e-08, 2.2370386e-08, 1.6954198e-06, 4.0116068e-04,
        6.0060680e-12, 3.6392487e-07, 1.1597856e-16, 9.9956936e-01,
        2.7476227e-07, 2.7187554e-05]], dtype=float32)>

In [69]:
x_test[:1].shape

(1, 28, 28)

In [70]:
x_test2 = x_test[:1].reshape((28,28))

In [71]:
def tensor_to_image(tensor):
    tensor = tensor*255
    tensor = np.array(tensor, dtype=np.uint8)
    if np.ndim(tensor)>3:
        assert tensor.shape[0] == 1
        tensor = tensor[0]
    return Image.fromarray(tensor)

In [72]:
tensor_to_image(x_test2)